version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: crm_postgres
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
      POSTGRES_DB: crm_db
    ports:
      - "5433:5432" # Порт 5433, як у презентації
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: